
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CrudEmpService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9090/SOAPD2L3/employee?WSDL")
public class CrudEmpService
    extends Service
{

    private final static URL CRUDEMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRUDEMPSERVICE_EXCEPTION;
    private final static QName CRUDEMPSERVICE_QNAME = new QName("http://service/", "CrudEmpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/SOAPD2L3/employee?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRUDEMPSERVICE_WSDL_LOCATION = url;
        CRUDEMPSERVICE_EXCEPTION = e;
    }

    public CrudEmpService() {
        super(__getWsdlLocation(), CRUDEMPSERVICE_QNAME);
    }

    public CrudEmpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRUDEMPSERVICE_QNAME, features);
    }

    public CrudEmpService(URL wsdlLocation) {
        super(wsdlLocation, CRUDEMPSERVICE_QNAME);
    }

    public CrudEmpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRUDEMPSERVICE_QNAME, features);
    }

    public CrudEmpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrudEmpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrudEmp
     */
    @WebEndpoint(name = "CrudEmpPort")
    public CrudEmp getCrudEmpPort() {
        return super.getPort(new QName("http://service/", "CrudEmpPort"), CrudEmp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrudEmp
     */
    @WebEndpoint(name = "CrudEmpPort")
    public CrudEmp getCrudEmpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "CrudEmpPort"), CrudEmp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRUDEMPSERVICE_EXCEPTION!= null) {
            throw CRUDEMPSERVICE_EXCEPTION;
        }
        return CRUDEMPSERVICE_WSDL_LOCATION;
    }

}
